const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
const GET_CATEGORY = 'GET_CATEGORY'


module.exports = {
	GET_ALL_PRODUCTS,
	GET_ALL_CATEGORIES,
	GET_CATEGORY
}