const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
const GET_ALL_SIZES = "GET_ALL_SIZES";
const GET_ALL_TYPES = "GET_ALL_TYPES";
const GET_CATEGORY = "GET_CATEGORY";
const GET_TYPE = "GET_TYPE";
const GET_SEARCH = "GET_SEARCH";
const GET_FILTER_BY_PRICE = "GET_FILTER_BY_PRICE";
const POST_PRODUCT = "POST_PRODUCT";
const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
const POST_CATEGORIES = "POS_CATEGORIES";
const GET_UPDATE_PRODUCT_DETAILS = "GET_UPDATE_PRODUCT_DETAILS";
const CLEAN_UPDATE_PRODUCT_DETAILS = "CLEAN_UPDATE_PRODUCT_DETAILS";

module.exports = {
	GET_ALL_PRODUCTS,
	GET_ALL_CATEGORIES,
	GET_ALL_TYPES,
  GET_ALL_SIZES,		
	GET_CATEGORY,
	GET_TYPE,
	GET_SEARCH,	
	GET_FILTER_BY_PRICE,
  POST_PRODUCT,
  POST_CATEGORIES,
  GET_PRODUCT_DETAILS,
	GET_UPDATE_PRODUCT_DETAILS,
	CLEAN_UPDATE_PRODUCT_DETAILS
 }


