const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
const GET_ALL_SIZES = "GET_ALL_SIZES";
const GET_ALL_TYPES = "GET_ALL_TYPES";
const GET_CATEGORY = "GET_CATEGORY";
const GET_TYPE = "GET_TYPE";
const GET_SEARCH = "GET_SEARCH";
const GET_FILTER_BY_PRICE = "GET_FILTER_BY_PRICE";
const POST_PRODUCT = "POST_PRODUCT";
const GET_CONTADOR = "GET_CONTADOR";
const ADD_TO_BASKET = "ADD_TO_BASKET";
const REMOVE_ITEM = "REMOVE_ITEM";
const REMOVE_ITEM_USER = "REMOVE_ITEM_USER";
const EMPTY_BASKET = "EMPTY_BASKET";
const SET_USER = "SET_USER";
const SET_SHIPPINGDATA = "SET_SHIPPINGDATA";
const SET_PAYMENT_MESSAGE = "SET_PAYMENT_MESSAGE";
const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
const POST_LOGIN = "POST_LOGIN";
const POST_SIGNUP = "POST_SIGNUP";
const GET_USER = "GET_USER";
const GET_USERS = "GET_USER";
const GET_LOGOUT = "GET_LOGOUT";
const POST_CATEGORIES = "POS_CATEGORIES";
const GET_UPDATE_PRODUCT_DETAILS = "GET_UPDATE_PRODUCT_DETAILS";
const CLEAN_DETAIL_P_OBGETO = "CLEAN_DETAIL_P_OBGETO";
const RESTA_CONTADOR = "RESTA_CONTADOR";
const SUMA_CONTADOR = "SUMA_CONTADOR";
const CLEAN_UPDATE_PRODUCT_DETAILS = "CLEAN_UPDATE_PRODUCT_DETAILS";
const GET_ALL_CART = "GET_ALL_CART";
const GET_UPDATE_CATEGORY_DETAILS = "GET_UPDATE_CATEGORY_DETAILS" ;
const GET_UPDATE_TYPE_DETAILS = "GET_UPDATE_TYPE_DETAILS" ;
const GET_UPDATE_SIZE_DETAILS = "GET_UPDATE_SIZE_DETAILS";
const GET_GOOGLE_LOGIN = 'GET_GOOGLE_LOGIN';
const POST_CART = "POST_CART";
const PUT_CART = "PUT_CART";
const PUT_CART_USER = "PUT_CART_USER";
const GET_ALL_USER_DETAILS = "GET_ALL_USER_DETAILS";
const POST_USER_DETAILS = "POST_USER_DETAILS";
const GET_USER_ID_PARAMS = "GET_USER_ID_PARAMS"; 
const GET_USER_DETAIL = "GET_USER_DETAIL";
const POST_CART_USER = "POST_CART_USER";
const GET_ALL_CART_USER = "GET_ALL_CART_USER";
const GET_ALL_CART_TOTAL_USER = "GET_ALL_CART_TOTAL_USER";
const POST_VIEW_PU = "POST_VIEW_PU";
const GET_ALL_RATINGS = "GET_ALL_RATINGS";
const GET_RATING_DETAIL = "GET_RATING_DETAIL";
const GET_ALL_VIEWS = "GET_ALL_VIEWS"


module.exports = {
  GET_ALL_PRODUCTS,
  GET_ALL_CATEGORIES,
  GET_ALL_TYPES,
  GET_ALL_SIZES,
  GET_CONTADOR,
  GET_CATEGORY,
  GET_TYPE,
  GET_SEARCH,
  GET_FILTER_BY_PRICE,
  GET_PRODUCT_DETAILS,
  POST_LOGIN,
  POST_SIGNUP,
  GET_USER,
  GET_USERS,
  GET_LOGOUT,
  POST_PRODUCT,
  ADD_TO_BASKET,
  REMOVE_ITEM,
  EMPTY_BASKET,
  SET_USER,
  SET_SHIPPINGDATA,
  SET_PAYMENT_MESSAGE,
  POST_CATEGORIES,
  GET_UPDATE_PRODUCT_DETAILS,
  CLEAN_DETAIL_P_OBGETO,
  SUMA_CONTADOR,
  RESTA_CONTADOR,
  CLEAN_UPDATE_PRODUCT_DETAILS,
  GET_ALL_CART,
  GET_UPDATE_CATEGORY_DETAILS,
  GET_UPDATE_TYPE_DETAILS,
  GET_UPDATE_SIZE_DETAILS,
  GET_GOOGLE_LOGIN,
  POST_CART,
  PUT_CART,
  GET_ALL_USER_DETAILS,
  POST_USER_DETAILS,
  GET_USER_ID_PARAMS,
  GET_USER_DETAIL,
  POST_CART_USER,
  GET_ALL_CART_USER,
  GET_ALL_CART_TOTAL_USER,
  PUT_CART_USER,
  REMOVE_ITEM_USER,
  POST_VIEW_PU,
  GET_ALL_RATINGS,
  GET_RATING_DETAIL,
  GET_ALL_VIEWS
};
